import type { Metadata } from 'next'
import { Raleway, Roboto } from 'next/font/google'
import '@fortawesome/fontawesome-svg-core/styles.css'
import './globals.css'

import Navbar from './(components)/Navbar'
import Footer from './(components)/Footer'

const roboto = Roboto({ 
  subsets: ['latin'],
  weight: "400",
})

export const metadata: Metadata = {
  title: 'Ticket App',
  description: 'Generated by Jonatas Santos',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="flex flex-col h-screen max-h-screen">
          <Navbar />
          <div className="flex-grow overflow-y-auto bg-slate-800 text-default-text">
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  )
}
