import type { Metadata } from 'next'
import { Raleway } from 'next/font/google'
import '@fortawesome/fontawesome-svg-core/styles.css'
import './globals.css'

import Navbar from './(components)/Navbar'
import Footer from './(components)/Footer'

const raleway = Raleway({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Ticket App',
  description: 'Generated by Jonatas Santos',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <div className="flex flex-col h-screen max-h-screen">
          <Navbar />
          <div className="flex-grow overflow-y-auto bg-slate-500 text-default-text">
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  )
}
